"""`.github/scripts/checks/tla-model-check.py` tells a failing config which
emitter regenerates its module.

PROBLEM CLASS — a remedy message that names ONE module for every failure. The
hint then sends the reader to the wrong emitter, and `uv run python -m
tests._ladder_fsm_tla` reports success while the stale module stays stale.
`AutoResolve.tla` is printed by `tests/_outcome_fsm_tla.py`, so no rule maps a
module name to its emitter: the module's own header is the only source.
"""

import importlib.util
from pathlib import Path

from tests._helpers import REPO_ROOT

CHECK = REPO_ROOT / ".github" / "scripts" / "checks" / "tla-model-check.py"


def _load():
    spec = importlib.util.spec_from_file_location("tla_model_check", CHECK)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


checker = _load()


def _case(cfg: Path, module: str):
    return checker.Case(cfg=cfg, module=module, want=0, liveness=False, distinct=None)


def _module(tmp_path: Path, name: str, emitter: str | None) -> Path:
    body = f"---- MODULE {name} ----\n"
    if emitter:
        body += f"(* generated by tests/{emitter}.py *)\n"
    (tmp_path / f"{name}.tla").write_text(body + "====\n", encoding="utf-8")
    return tmp_path / f"{name}.cfg"


def test_the_hint_names_the_emitter_the_failing_module_declares(tmp_path) -> None:
    cfg = _module(tmp_path, "AutoResolve", "_outcome_fsm_tla")
    hint = checker.regenerate_hint([_case(cfg, "AutoResolve")])
    assert "tests._outcome_fsm_tla" in hint
    assert "_ladder_fsm_tla" not in hint


def test_two_failing_modules_each_get_their_own_emitter(tmp_path) -> None:
    """The case a fixed remedy gets wrong even when its one module is right: a
    run that reds two configs needs both commands, not the first one twice."""
    left = _module(tmp_path, "Handoff", "_handoff_fsm_tla")
    right = _module(tmp_path, "Ladder", "_ladder_fsm_tla")
    hint = checker.regenerate_hint([_case(left, "Handoff"), _case(right, "Ladder")])
    assert "tests._handoff_fsm_tla" in hint
    assert "tests._ladder_fsm_tla" in hint


def test_a_module_that_names_no_emitter_gets_no_command(tmp_path) -> None:
    """A hand-written module is edited where it lives. A regenerate command for
    one would tell the reader to run something that does not exist."""
    cfg = _module(tmp_path, "HandWritten", None)
    assert checker.regenerate_hint([_case(cfg, "HandWritten")]) == ""


def test_a_missing_module_file_is_not_an_error(tmp_path) -> None:
    """The hint runs on the failure path, so it never raises there: a config
    naming no module on disk already reds for that, with its own message."""
    assert checker.regenerate_hint([_case(tmp_path / "Gone.cfg", "Gone")]) == ""


def test_every_committed_module_the_checker_reads_declares_its_emitter() -> None:
    """The hint is only useful while the generated modules say who prints them.
    A new generated module without that line silently loses its remedy."""
    specs = REPO_ROOT / "docs" / "tla"
    generated = [
        p
        for p in sorted(specs.glob("*.tla"))
        if "GENERATED" in p.read_text(encoding="utf-8")
    ]
    assert generated
    for module in generated:
        assert checker.EMITTER.search(module.read_text(encoding="utf-8")), module.name
